<a href="https://colab.research.google.com/github/alanantony444/ict-assignment/blob/main/Data_Pro_assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Question 1.**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/employee (1).csv')

In [3]:
df.shape

(9, 7)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               9 non-null      object
 1   age                7 non-null      float64
 2   income             7 non-null      float64
 3   gender             7 non-null      object
 4   department         9 non-null      object
 5   grade              9 non-null      object
 6   performance_score  9 non-null      int64
dtypes: float64(2), int64(1), object(4)
memory usage: 636.0+ bytes

In [5]:
df.head()

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

# **Question 2.**

# Setting the column "name" as the index.

In [6]:
df.set_index('name', inplace=True)

In [7]:
df.head((5))

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
S Kumar         NaN  16000.0      F     Finance    G0                520
Jack Morgan    32.0  35000.0      M     Finance    G2                674
Ying Chin      45.0  65000.0      F       Sales    G3                556
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

# **Question 3.**

# Display of employee who has more than 700 performance score

In [8]:
emp_700 = df[df['performance_score'] > 700]
print("Employees with a performance score over 700:")
display(emp_700)

Employees with a performance score over 700:

                age   income gender  department grade  performance_score
name
Allen Smith    45.0      NaN    NaN  Operations    G3                723
Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
Josh Wills     54.0  52000.0      F     Finance    G3                901
Leo Duck       23.0  98000.0      M       Sales    G4                709

# **Question 4.**

# Displaying of employee who has more than 500 and less than 700 performance score

In [9]:
mid_per = df.query('500 < performance_score < 700')

In [10]:
print("Employees in the 500-700 range:",mid_per)

Employees in the 500-700 range:                 age   income gender department grade  performance_score
name
S Kumar         NaN  16000.0      F    Finance    G0                520
Jack Morgan    32.0  35000.0      M    Finance    G2                674
Ying Chin      45.0  65000.0      F      Sales    G3                556
Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649

# **Question 5.**

# Checked and handled missing values in the dataset

In [12]:
# Check missing values
print(df.isnull().sum())
df.fillna(df.mean(numeric_only=True), inplace=True)
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

age                  0
income               0
gender               0
department           0
grade                0
performance_score    0
dtype: int64

/tmp/ipykernel_708/1873931131.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0], inplace=True)

# **question 6**

# Check the outliers and handle outliers in performance score using Percentiles

In [13]:
# Define percentiles
lower = df['performance_score'].quantile(0.05)
upper = df['performance_score'].quantile(0.95)
df = df[(df['performance_score'] >= lower) & (df['performance_score'] <= upper)]
print(df)

                     age        income gender  department grade  \
name
Allen Smith    45.000000  52857.142857      F  Operations    G3
S Kumar        40.428571  16000.000000      F     Finance    G0
Jack Morgan    32.000000  35000.000000      M     Finance    G2
Ying Chin      45.000000  65000.000000      F       Sales    G3
Dheeraj Patel  30.000000  42000.000000      F  Operations    G2
Satyam Sharma  40.428571  62000.000000      F       Sales    G3
Leo Duck       23.000000  98000.000000      M       Sales    G4

               performance_score
name
Allen Smith                  723
S Kumar                      520
Jack Morgan                  674
Ying Chin                    556
Dheeraj Patel                711
Satyam Sharma                649
Leo Duck                     709

# **Question 7**

# Check the gender column and do one hot encoding.

In [14]:
# One-hot encoding
df = pd.get_dummies(df, columns=['gender'])
print(df.head())

                     age        income  department grade  performance_score  \
name
Allen Smith    45.000000  52857.142857  Operations    G3                723
S Kumar        40.428571  16000.000000     Finance    G0                520
Jack Morgan    32.000000  35000.000000     Finance    G2                674
Ying Chin      45.000000  65000.000000       Sales    G3                556
Dheeraj Patel  30.000000  42000.000000  Operations    G2                711

               gender_F  gender_M
name
Allen Smith        True     False
S Kumar            True     False
Jack Morgan       False      True
Ying Chin          True     False
Dheeraj Patel      True     False